[project]
name = "pytest-parallel-example"
version = "1.0.0"
description = "Python pytest example running in parallel on Buildkite"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.2",
    "pytest-retry>=1.7.0",
    "pytest-split>=0.10.0",
]
